<?php

namespace Database\Seeders;

use App\Models\Proveedor;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProveedorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $proveedores = [
            [
                'nombre' => 'Bayer Farmacéutica',
                'nit' => '890900000-1',
                'telefono' => '(1) 7894050',
                'email' => 'ventas@bayer.com.co',
                'direccion' => 'Carrera 7 No. 156-56',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Carlos Mendoza',
                'telefono_contacto' => '3105678901',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Proveedor principal de analgésicos e antiinflamatorios',
            ],
            [
                'nombre' => 'Pfizer Colombia',
                'nit' => '890800000-2',
                'telefono' => '(1) 5555555',
                'email' => 'sales@pfizer.com.co',
                'direccion' => 'Avenida El Dorado km 10',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'María García',
                'telefono_contacto' => '3128765432',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Distribuidor de antibióticos y cardiovasculares',
            ],
            [
                'nombre' => 'GlaxoSmithKline Andina',
                'nit' => '890700000-3',
                'telefono' => '(1) 3216540',
                'email' => 'clientes@gsk.com.co',
                'direccion' => 'Calle 100 No. 10-50',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Juan Pérez',
                'telefono_contacto' => '3119876543',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Especialista en medicamentos respiratorios',
            ],
            [
                'nombre' => 'Novartis Pharma S.A.',
                'nit' => '890600000-4',
                'telefono' => '(1) 4321987',
                'email' => 'ventas@novartis.com.co',
                'direccion' => 'Carrera 11 No. 98-65',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Roberto López',
                'telefono_contacto' => '3007654321',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Proveedor de antiinflamatorios y cardiovasculares',
            ],
            [
                'nombre' => 'Sanofi Pasteur Colombia',
                'nit' => '890500000-5',
                'telefono' => '(1) 5432100',
                'email' => 'info@sanofi.com.co',
                'direccion' => 'Calle 93 No. 11-50',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Patricia Rodríguez',
                'telefono_contacto' => '3156789012',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Distribuidor de antibióticos y digestivos',
            ],
            [
                'nombre' => 'Abbott Laboratorios',
                'nit' => '890400000-6',
                'telefono' => '(1) 6789012',
                'email' => 'ventas@abbott.com.co',
                'direccion' => 'Avenida Caracas No. 54-20',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Fernando Díaz',
                'telefono_contacto' => '3175431098',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Proveedor de analgésicos y antihistamínicos',
            ],
            [
                'nombre' => 'Roche Farma S.A.',
                'nit' => '890300000-7',
                'telefono' => '(1) 7890123',
                'email' => 'sales@roche.com.co',
                'direccion' => 'Carrera 9 No. 75-42',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Alejandra Martínez',
                'telefono_contacto' => '3209876543',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Especialista en respiratorios y dermatológicos',
            ],
            [
                'nombre' => 'Merck Sharp & Dohme',
                'nit' => '890200000-8',
                'telefono' => '(1) 8901234',
                'email' => 'contact@merck.com.co',
                'direccion' => 'Calle 82 No. 12-70',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Daniela Soto',
                'telefono_contacto' => '3218765432',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Distribuidor de antihistamínicos y cardiovasculares',
            ],
            [
                'nombre' => 'Genfar S.A.',
                'nit' => '890100000-9',
                'telefono' => '(1) 9012345',
                'email' => 'ventas@genfar.com.co',
                'direccion' => 'Avenida Villavicencio No. 65-85',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Diego Ramírez',
                'telefono_contacto' => '3126543210',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Laboratorio nacional productor de genéricos',
            ],
            [
                'nombre' => 'AstraZeneca Latinoamérica',
                'nit' => '890000000-0',
                'telefono' => '(1) 2345678',
                'email' => 'info@astrazeneca.com.co',
                'direccion' => 'Carrera 13 No. 65-50',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Silvia González',
                'telefono_contacto' => '3137654321',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Proveedor de digestivos y cardiovasculares',
            ],
            [
                'nombre' => '3M Health Care Colombia',
                'nit' => '860000000-1',
                'telefono' => '(1) 3456789',
                'email' => 'sales@3m.com.co',
                'direccion' => 'Calle 116 No. 9-80',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Ricardo Álvarez',
                'telefono_contacto' => '3148765432',
                'categoria' => 'Material Médico',
                'observaciones' => 'Distribuidor de material de curación',
            ],
            [
                'nombre' => 'Johnson & Johnson Colombia',
                'nit' => '860100000-2',
                'telefono' => '(1) 4567890',
                'email' => 'contact@jnj.com.co',
                'direccion' => 'Autopista Medellín km 15',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Carolina López',
                'telefono_contacto' => '3159876543',
                'categoria' => 'Material Médico',
                'observaciones' => 'Proveedor de material de curación y dermatológicos',
            ],
            [
                'nombre' => 'Halyard Health Latam',
                'nit' => '860200000-3',
                'telefono' => '(1) 5678901',
                'email' => 'ventas@halyard.com.co',
                'direccion' => 'Avenida Eldorado No. 78-45',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Andrés Castillo',
                'telefono_contacto' => '3167654321',
                'categoria' => 'Material Médico',
                'observaciones' => 'Especialista en guantes y equipos de protección',
            ],
            [
                'nombre' => 'Becton Dickinson Ltda.',
                'nit' => '860300000-4',
                'telefono' => '(1) 6789012',
                'email' => 'info@bd.com.co',
                'direccion' => 'Carrera 15 No. 45-87',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Natalia Reyes',
                'telefono_contacto' => '3178765432',
                'categoria' => 'Material Médico',
                'observaciones' => 'Proveedor de jeringas y agujas',
            ],
            [
                'nombre' => 'Medifarma S.A.',
                'nit' => '860400000-5',
                'telefono' => '(1) 7890123',
                'email' => 'ventas@medifarma.com.co',
                'direccion' => 'Calle 71 No. 10-25',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Gustavo Morales',
                'telefono_contacto' => '3189876543',
                'categoria' => 'Material Médico',
                'observaciones' => 'Distribuidor de alcohol antiséptico y agua oxigenada',
            ],
            [
                'nombre' => 'Zambon Andina S.A.',
                'nit' => '860500000-6',
                'telefono' => '(1) 8901234',
                'email' => 'sales@zambon.com.co',
                'direccion' => 'Carrera 7 No. 114-36',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Gabriela Ortiz',
                'telefono_contacto' => '3191234567',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Especialista en medicamentos respiratorios',
            ],
            [
                'nombre' => 'Takeda Farmacéutica',
                'nit' => '860600000-7',
                'telefono' => '(1) 9012345',
                'email' => 'info@takeda.com.co',
                'direccion' => 'Calle 127 No. 8-50',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Héctor Vargas',
                'telefono_contacto' => '3202345678',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Distribuidor de digestivos',
            ],
            [
                'nombre' => 'Biocodex Colombia',
                'nit' => '860700000-8',
                'telefono' => '(1) 2345678',
                'email' => 'ventas@biocodex.com.co',
                'direccion' => 'Avenida Cra. 9 No. 45-50',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Verónica Silva',
                'telefono_contacto' => '3213456789',
                'categoria' => 'Suplementos',
                'observaciones' => 'Especialista en probióticos y suplementos',
            ],
            [
                'nombre' => 'Boehringer Ingelheim',
                'nit' => '860800000-9',
                'telefono' => '(1) 3456789',
                'email' => 'contact@boehringer.com.co',
                'direccion' => 'Calle 90 No. 13-40',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Fátima Molina',
                'telefono_contacto' => '3224567890',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Distribuidor de digestivos y respiratorios',
            ],
            [
                'nombre' => 'Leo Pharma Group',
                'nit' => '860900000-0',
                'telefono' => '(1) 4567890',
                'email' => 'sales@leopharma.com.co',
                'direccion' => 'Carrera 11A No. 93-50',
                'ciudad' => 'Bogotá',
                'pais' => 'Colombia',
                'contacto' => 'Marcela Fuentes',
                'telefono_contacto' => '3235678901',
                'categoria' => 'Medicamentos',
                'observaciones' => 'Especialista en dermatológicos',
            ],
        ];

        foreach ($proveedores as $proveedor) {
            Proveedor::firstOrCreate(
                ['nit' => $proveedor['nit']],
                [
                    'id' => Str::uuid(),
                    'nombre' => $proveedor['nombre'],
                    'telefono' => $proveedor['telefono'],
                    'email' => $proveedor['email'],
                    'direccion' => $proveedor['direccion'],
                    'ciudad' => $proveedor['ciudad'],
                    'pais' => $proveedor['pais'],
                    'contacto' => $proveedor['contacto'],
                    'telefono_contacto' => $proveedor['telefono_contacto'],
                    'categoria' => $proveedor['categoria'],
                    'observaciones' => $proveedor['observaciones'],
                    'estado' => 'activo',
                ]
            );
        }

        $this->command->info('Proveedores seed completado correctamente. Se crearon 20 proveedores.');
    }
}
